<?php

use app\core\entity\Form;
use app\core\entity\Message;
use app\core\entity\WhoAmI;
use app\core\model\SingleModel;

include_once("header.php");

function getMsg() : string {
    if(isset($_GET['msg_id'])) {
        if(Message::SUCCESS_MSG->value != $_GET['msg_id']) {
            return Message::getMessage(Message::get($_GET['msg_id']));
        }else {
            return "Votre demande d'inscription a été envoyée aves succès.<br>";
        }
    }
    return "";
}

$singleModel = new SingleModel;

(new Form)->add('<section class="vh-100 gradient-custom">')
->add('<div class="container py-5 h-100">')
->add('<div class="row justify-content-center align-items-center h-100">')
->add('<div class="col-12 col-lg-9 col-xl-7">')
->add('<div class="card shadow-2-strong card-registration" style="border-radius: 15px;">')
->add('<div class="card-body p-4 p-md-5">')
->add('<h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Formulaire de demande d\'inscription sur le portail de ' . APP_NAME . '</h3>')
->add('<form action="request_signup" method="post">')
->add('<div class="row">')
->add('<div class="mb-2 align-items-center">')
->add('<span class="error-msg align-items-center" id="details">')
->add(getMsg())
->add('</span>')
->add('</div>')
->add('</div>')
->add('<div class="row">')
->add('<div class="col-md-6 mb-4">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<input class="form-control form-control-lg" type="text" id="first_name" name="first_name" />')
->add('<label class="form-label" for="first_name">Prénom</label>')
->add('</div>')
->add('</div>')
->add('<div class="col-md-6 mb-4">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<input class="form-control form-control-lg" type="text" id="last_name" name="last_name" />')
->add('<label class="form-label" for="last_name">Nom</label>')
->add('</div>')
->add('</div>')
->add('</div>')
->add('<div class="row">')
->add('<div class="col-md-6 mb-4">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<select class="select form-control form-control-lg" id="gender" name="gender">')
->add($singleModel->setTable("genders")->getAllAsOptions())
->add('</select>')
->add('<label class="form-label" for="gender">Sexe</label>')
->add('</div>')
->add('</div>')
->add('<div class="col-md-6 mb-4">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<select class="select form-control form-control-lg" id="department" name="department">')
->add($singleModel->setTable("departments")->getAllAsOptions())
->add('</select>')
->add('<label class="form-label" for="department">Département</label>')
->add('</div>')
->add('</div>')
->add('</div>')
->add('<div class="row">')
->add('<div class="col-md-6 mb-4 pb-2">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<input class="form-control form-control-lg" type="email" id="email" name="email" />')
->add('<label class="form-label" for="email">Email</label>')
->add('</div>')
->add('</div>')
->add('<div class="col-md-6 mb-4 pb-2">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<input class="form-control form-control-lg" type="tel" id="phone" name="phone" />')
->add('<label class="form-label" for="phone">Téléphone</label>')
->add('</div>')
->add('</div>')
->add('</div>')
->add('<div class="row">')
->add('<div class="col-md-4 mb-4">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<select class="select form-control form-control-lg" id="whoami" name="whoami">')
->add($singleModel->setTable("whoami")->getAllAsOptions(
    1, [WhoAmI::ADM->value]
))
->add('</select>')
->add('<label class="form-label" for="whoami">Statut</label>')
->add('</div>')
->add('</div>')
->add('<div class="col-md-4 mb-4">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<select class="select form-control form-control-lg" id="section" name="section">')
->add($singleModel->setTable("sections")->getAllAsOptions())
->add('</select>')
->add('<label class="form-label" for="section">Section</label>')
->add('</div>')
->add('</div>')
->add('<div class="col-md-4 mb-4">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<select class="select form-control form-control-lg" id="grade" name="grade">')
->add($singleModel->setTable("grades")->getAllAsOptions())
->add('</select>')
->add('<label class="form-label" for="grade">Niveau d\'étude</label>')
->add('</div>')
->add('</div>')
->add('</div>')
->add('<div class="row">')
->add('<div class="mb-4 pb-2">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<input class="form-control form-control-lg" type="text" id="user_name" name="user_name" />')
->add('<label class="form-label" for="user_name">Identifiant</label>')
->add('</div>')
->add('</div>')
->add('</div>')
->add('<div class="row">')
->add('<div class="col-md-6 mb-4 pb-2">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<input class="form-control form-control-lg" type="password" id="pwd" name="pwd" />')
->add('<label class="form-label" for="pwd">Mot de passe</label>')
->add('</div>')
->add('</div>')
->add('<div class="col-md-6 mb-4 pb-2">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<input class="form-control form-control-lg" type="password" id="conf_pwd" name="conf_pwd" />')
->add('<label class="form-label" for="conf_pwd">Confirmer mot de passe</label>')
->add('</div>')
->add('</div>')
->add('</div>')
->add('<div class="mt-1 pt-2">')
->add('<input data-mdb-ripple-init class="btn btn-primary btn-lg" type="submit" value="Soumettre la demande" />')
->add('</div>')
->add('<div class="row">')
->add('<div class="mt-2">')
->add('<div data-mdb-input-init class="form-outline">')
->add('<span>Déjà inscrit ? <a href="login">Se connecter</a> sur le portail de <?=APP_NAME?> !</span>')
->add('</div>')
->add('</div>')
->add('</div>')
->add('</form>')
->add('</div>')
->add('</div>')
->add('</div>')
->add('</div>')
->add('</div>')
->add('</section>')
->show();

include_once("footer.php");